"""first migrations

Revision ID: bae7fd47408a
Revises: 
Create Date: 2024-03-27 05:31:30.900232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae7fd47408a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitcoin_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('exchange', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.String(length=50), nullable=True),
    sa.Column('participant_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('sip_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bitcoin_price')
    # ### end Alembic commands ###
